global.switchValue;
global.backgroundColor;
global.CurrentColor;
global.SwitchLogin;
global.SwitchRegister;
global.SwitchUser;
global.SunMoon;
global.TextColor;
global.separator;
global.MichaelsDreck = "Filip";
